# Configuraci칩n para Netlify
[build]
  command = "bun run build"
  publish = ".next"

[functions]
  # Permite que las funciones serverless tengan un tiempo de ejecuci칩n m치s largo
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  # Permitir la carga de im치genes remotas
  remote_images = ["https://same-assets.com/.*", "https://ext.same-assets.com/.*", "https://upload.wikimedia.org/.*"]
