# Configuración optimizada de Netlify para Space People Counter
[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  # Variables de entorno para el build
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Plugin oficial de Next.js para Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración de funciones serverless
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  
# Headers de seguridad y optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
# Cache optimizado para assets estáticos
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para imágenes del public folder
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    
# Cache para iconos específicamente
[[headers]]
  for = "/images/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Cache para API responses (más conservador)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=60, s-maxage=300"
    
# Redirects para manejo de rutas
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect para trailing slashes
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
